### ISSUE TITLE
CloudWatch Logger node generating a lot of logging info

### ISSUE THREAD

**Issue by mr337** [aws-robotics/cloudwatchlogs-ros1#20]
Reviewing logs that are coming in and finding the cloudwatch_logger node itself generating a ton of INFO messages that seems to be consistent with the `publish_frequency`. The original 5s interval hit a API limit compared to the little logs our application sends.

Here is a logs with a 60s frequency with `min_log_verbosity` set to `INFO`. We are concious about uncessary logs since these are shipped over cellular.

![logs](https://user-images.githubusercontent.com/413937/55451189-7f8ed300-5597-11e9-98ef-8c080ae566b8.png)

Is it possible to suppress this logging from the node vs bumping our logging levels within our entire application? Or would it be better to set `sub_to_rosout` to `False` and start pushing logs to a dedicated topic?

Any guidance appreciated!

**Comment by mr337** [comment]
Actually getting pages and pages of these logs now, so much that after a while start getting 400 error codes with `publish_frequency` set to 60s.

```[ERROR] [1554262994.235894224, 783.613000000]: [AWSClient] HTTP response code: 400
Exception name: ThrottlingException
Error message: Rate exceeded
5 response headers:
connection : close
content-length : 58
content-type : application/x-amz-json-1.1
date : Wed, 03 Apr 2019 03:43:13 GMT
x-amzn-requestid : 9c0f1086-55c2-11e9-9a3c-dd03191bb437
[ERROR] [1554263054.735471703, 843.489000000]: [AWSClient] HTTP response code: 400
Exception name: ThrottlingException
Error message: Rate exceeded
```

I can pull the logs down and start running numbers on them, but it looks to be surely spamming. Here is my overall config in the launch file.

```
  <node name="cloud_logger" pkg="cloudwatch_logger" type="cloudwatch_logger">
    <param  name="sub_to_rosout" value="true" />
    <param  name="log_group_name" value="testgroup" />
    <param  name="log_stream_name" value="teststream" />
    <param  name="publish_frequency" value="60" />
    <param  name="min_log_verbosity" value="INFO" />
    <param  name="aws_client_configuration/region" value="us-east-1" />
  </node>
```

**Comment by AAlon** [comment]
Thanks for reporting this issue, it's definitely something we'd like to resolve quickly as it affects the actual usability of the node.

If we change those from INFO to DEBUG, would that suffice as a long term solution or would it help to be able to omit all those "meta logs"? One option is a launch parameter that would control the threshold severity for the node's own logs, so that if you set it to NONE, none of these logs you mentioned would appear. We'd appreciate your thoughts.

Meanwhile, to unblock you, there are two options:

1.Build the node from source with `ROSCONSOLE_MIN_SEVERITY=5` - this should remove all logging by the node (e.g. `colcon build --cmake-args ' -DROSCONSOLE_MIN_SEVERITY=5'`). If you installed the node via `apt`, make sure you clone the same version as you have now (as the tip of `master` is incompatible with the version currently in `apt`).
2. I've changed the offending logs from INFO to DEBUG and pushed the fix into a branch that can be cloned right away, see instructions below.

#### Using the patched branch
You'll need to build the cloudwatch_logger and cloudwatch_logs_common from source, and also use the latest version of the dependencies. Steps: (assuming you've installed via `apt`)

1. Remove existing installations & dependencies: `apt remove ros-kinetic-aws-common`, `apt remove ros-kinetic-aws-ros1-common` should suffice.
2. Update `/etc/apt/sources.list.d/ros-latest.list` to use `ros-shadow-fixed` as per http://wiki.ros.org/ShadowRepository and `apt update`
4. Create a cloudwatch workspace with src dir, and clone into src (note the branches/tags):
   * https://github.com/aws-robotics/cloudwatchlogs-ros1/tree/2.0.0 
   * https://github.com/aws-robotics/cloudwatch-common/tree/decreased-log-severity
5. `rosdep install --from-paths src --ignore-src -r -y` to install the latest dependencies.
6. Make any adjustments to launch/config files, build (i.e. `colcon build`), source the appropriate setup file, and run as before.

**Comment by AAlon** [comment]
After reviewing the code again - there is a much easier way for you to avoid this problem. We already have a mechanism in place to omit logs from the cloudwatch logger node, it's just that it was set for the hard-coded node name, and assumes that it's `cloudwatch_logger` (see [code](https://github.com/aws-robotics/cloudwatchlogs-ros1/blob/master/cloudwatch_logger/src/log_node.cpp#L47)). 

In your configuration you set `node name="cloud_logger"`, which caused those logs to be emitted... so if you just use the default node name, `cloudwatch_logger`, you won't run into this issue. 

Of course, this is an issue in the implementation since we shouldn't rely on a hard-coded name but instead fetch the actual name at run time. We will take an action item to fix this.

Again, thanks for opening this and please let us know whether you managed to overcome the issue.

**Comment by mr337** [comment]
Excellent to hear! I'll test that quickly and verify if it help. Thank you for being prompt

**Comment by mr337** [comment]
Changing the node name to `cloudwatch_logger` worked.
