### ISSUE TITLE
add diagnostics support 

### ISSUE THREAD

**Issue by hakuturu583** [aws-robotics/cloudwatchlogs-ros1#52]
diagnostics is a ROS diagnostics package.
We publish CPU usage,actuator temperature etc...
So, it is important to support this message type.

**Comment by AAlon** [comment]
> diagnostics is a ROS diagnostics package.
> We publish CPU usage,actuator temperature etc...
> So, it is important to support this message type.

Hi @hakuturu583, since there are many different message types that users might want to emit to CloudWatch, we made a decision to support a single, relatively simple type into which you would need to convert your messages - `rosgraph_msgs/Log` for the CloudWatch Logs node, and `ros_monitoring_msgs/MetricList` for the CloudWatch Metrics node. 

Please let us know if you're having any issues converting your message type into those.

Furthermore, we have a health metric collector node which supports seamless metric emitting for some of the metrics you described, and we'd greatly appreciate any contributions or suggestions there, too: https://github.com/aws-robotics/health-metrics-collector-ros1

**Comment by cevans87** [comment]
Closing this. Feel free to reopen if you need to pursue it further.
